### PR TITLE
Room Building Prep

### PR DESCRIPTION
**Pull request by Garrett6419**
Added a bunch of Prefabs to make building rooms easier and make the room Hierarchy more readable

### CODE REVIEW

**Comment by JaredBaker99** [comment]
Need to add a camera to render the scene of the acid room.

**Review by JaredBaker99 — CHANGES_REQUESTED** [review]
Add camera to scene of acid romo

**Comment by Garrett6419** [comment]
Reworked all the Prefabs and the Acid Room

**Review by JaredBaker99 — CHANGES_REQUESTED** [review]
Everything looks good. Acid room controls are all backwards

**Comment by Garrett6419** [comment]
Should've fixed the backwards controls in the acid room and they should all be consistent now

**Review by JaredBaker99 — APPROVED** [review]

**Pull request merged**
